file(REMOVE_RECURSE "${OUTDIR}")
file(MAKE_DIRECTORY "${OUTDIR}")
function(run_case name text expect reject)
    file(WRITE "${OUTDIR}/${name}.script" "${text}")
    execute_process(COMMAND "${SCMDSIM}" "${OUTDIR}" --script "${OUTDIR}/${name}.script"
        --no-interactive --no-ansi ${ARGN}
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL 0 OR NOT out MATCHES "${expect}" OR (NOT "${reject}" STREQUAL "" AND out MATCHES "${reject}"))
        message(FATAL_ERROR "${name}: rc=${rc}\n${out}\n${err}")
    endif()
endfunction()
run_case(literal [=[alias msg "echoln C:\temp\notes\n\t"
msg
]=] [=[C:\\temp\\notes\\n\\t]=] "" --strict)
run_case(hidden "hideconsole;echoln HIDDEN_PRESERVED;showconsole\n:screen 2\n" "\\[screen\\]\nHIDDEN_PRESERVED" "" --strict)
run_case(delay "echo DELAYED;clear;echoln IMMEDIATE\n:screen 4\n:time\n" "\\[screen\\]\nIMMEDIATE\n\\[Console\\] DELAYED\n7 ms" "" --strict --echo-delay-ms 7)
file(WRITE "${OUTDIR}/leaf.cfg" "echoln CHILD\n")
run_case(loads "exec leaf;exec leaf.cfg\n:loads\n:stats\n" "2\tleaf\n.*sim_time=6ms.*execs=2.*unique_execs=1" "" --strict --exec-latency-ms 3)
string(REPEAT a 31 good)
string(REPEAT b 32 bad)
run_case(aliasnames "alias ${good} \"echoln NAME31_OK\"\nalias ${bad} \"echoln NAME32_BAD\"\n${good}\n:aliases\n:stats\n" "NAME31_OK.*rejected_aliases=1" "NAME32_BAD")
function(must_fail name text)
    file(WRITE "${OUTDIR}/${name}.script" "${text}")
    execute_process(COMMAND "${SCMDSIM}" "${OUTDIR}" --script "${OUTDIR}/${name}.script"
        --no-interactive --no-ansi --strict ${ARGN}
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(rc EQUAL 0)
        message(FATAL_ERROR "strict ${name} silently succeeded: ${out} ${err}")
    endif()
endfunction()
must_fail(unknown "wait\n")
must_fail(collision "alias sv_cheats \"echoln BAD\"\n")
must_fail(aliaslong "alias ${bad} \"echoln BAD\"\n")
must_fail(missing "exec missing.cfg\n")
string(REPEAT x 504 tail)
must_fail(commandlong "echoln ${tail}\n")
run_case(optional "execifexists missing;echoln OPTIONAL_OK\n" "OPTIONAL_OK" "" --strict)
string(REPEAT x 503 tail)
run_case(boundary "echoln ${tail}\n" "xxx" "Unknown" --strict)
string(REPEAT 中 168 chinese)
run_case(utf8boundary "echo ${chinese}\n" "中中" "" --strict)
must_fail(utf8long "echoln ${chinese}\n")
must_fail(overflow "sleep 1\nexec leaf\n" --exec-latency-ms 18446744073709551615)
file(WRITE "${OUTDIR}/escaped.cfg" [=[alias path "echoln C:\temp\n"
path
]=])
foreach(pass cold warm)
    run_case(cache_${pass} "exec escaped\n" [=[C:\\temp\\n]=] "" --strict --cache)
endforeach()
execute_process(COMMAND "${SCMDSIM}" "${OUTDIR}" --save-scb "${OUTDIR}/roundtrip.scb" --no-interactive --strict RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "SCB packaging failed")
endif()
execute_process(COMMAND "${SCMDSIM}" "${OUTDIR}/roundtrip.scb" --exec escaped --no-interactive --strict
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT rc EQUAL 0 OR NOT out MATCHES [=[C:\\temp\\n]=])
    message(FATAL_ERROR "SCB literal roundtrip failed: ${out} ${err}")
endif()
message(STATUS "SIM_FIDELITY_PASS: parser, hidden log, virtual timing, strict errors, names, limits, cache, SCB")
