foreach(suffix opt noopt)
    set(dir "${OUTDIR}/${suffix}")
    file(REMOVE_RECURSE "${dir}")
    file(MAKE_DIRECTORY "${dir}")
    set(extra)
    if(suffix STREQUAL "noopt")
        set(extra --no-opt)
    endif()
    execute_process(COMMAND "${SCMDC}" "${SOURCE}" -o "${dir}/output.cfg" --console-mode sync ${extra}
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "compile ${suffix} failed: ${out} ${err}")
    endif()
    execute_process(COMMAND "${SCMDSIM}" "${dir}" --exec output --no-interactive --no-engine-messages --no-ansi --strict --max-commands 20000000
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL 0 OR NOT out MATCHES "${EXPECT}" OR out MATCHES "_FAIL|Unknown command" OR err MATCHES "WARNING|couldn't exec")
        message(FATAL_ERROR "runtime ${suffix} failed: ${out} ${err}")
    endif()
endforeach()
