foreach(suffix opt noopt)
    set(dir "${OUTDIR}/${suffix}")
    file(REMOVE_RECURSE "${dir}")
    file(MAKE_DIRECTORY "${dir}")
    set(extra)
    if(suffix STREQUAL "noopt")
        set(extra --no-opt)
    endif()
    execute_process(COMMAND "${SCMDC}" "${SOURCE}" -o "${dir}/output.cfg" --console-mode sync ${extra}
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "compile: ${out} ${err}")
    endif()
    file(WRITE "${dir}/check.script" ":loads\n:stats\n:screen 8\n")
    execute_process(COMMAND "${SCMDSIM}" "${dir}" --exec output --script "${dir}/check.script"
        --strict --exec-latency-ms 2 --echo-delay-ms 7 --no-interactive --no-ansi
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT rc EQUAL 0 OR NOT out MATCHES "LAZY_SHARED_PASS" OR out MATCHES "_FAIL")
        message(FATAL_ERROR "runtime: ${out} ${err}")
    endif()
    string(REGEX MATCHALL "execing output.lazy/f0000/000.cfg" loads "${out}")
    list(LENGTH loads count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "shared function loaded ${count} times\n${out}")
    endif()
    file(READ "${dir}/output.cfg.loadmap.tsv" map)
    if(NOT map MATCHES "4\teager" OR NOT map MATCHES "5\teager" OR NOT map MATCHES "6\teager")
        message(FATAL_ERROR "resident closure missing: ${map}")
    endif()
    string(REGEX REPLACE ".*\\[screen\\]\n" "" screen "${out}")
    if(screen MATCHES "InputService" OR NOT screen MATCHES "RESIDENT_LEAF")
        message(FATAL_ERROR "resident frame is not clean: ${screen}")
    endif()
endforeach()
